from app import db

class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(100), nullable=False)
    nickname = db.Column(db.String(100))
    gender = db.Column(db.String(20))
    date_of_birth = db.Column(db.String(20))
    place_of_birth = db.Column(db.String(100))
    nationality = db.Column(db.String(100))
    address = db.Column(db.String(255))
    phone_number = db.Column(db.String(50))
    email_address = db.Column(db.String(100))
    occupation = db.Column(db.String(100))
    company = db.Column(db.String(100))
    job_title = db.Column(db.String(100))
    work_address = db.Column(db.String(255))
    work_phone_number = db.Column(db.String(50))
    work_email_address = db.Column(db.String(100))
    linkedin_profile = db.Column(db.String(255))
    marital_status = db.Column(db.String(20))
    spouse_name = db.Column(db.String(100))
    children_names_ages = db.Column(db.Text)
    hobbies = db.Column(db.Text)
    interests = db.Column(db.Text)
    favorite_books = db.Column(db.Text)
    favorite_movies = db.Column(db.Text)
    favorite_music = db.Column(db.Text)
    notes = db.Column(db.Text)
    social_media_profiles = db.Column(db.Text)
    date_met = db.Column(db.String(20))
    place_met = db.Column(db.String(100))
    first_impression = db.Column(db.Text)
    how_you_met = db.Column(db.Text)
    mutual_contacts = db.Column(db.Text)
    last_meeting_date = db.Column(db.String(20))
    next_meeting_date = db.Column(db.String(20))
    image_url = db.Column(db.String(255))  # Add this line