from app import db

class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(120), nullable=False)
    nickname = db.Column(db.String(80))
    gender = db.Column(db.String(20))
    date_of_birth = db.Column(db.String(20))
    place_of_birth = db.Column(db.String(120))
    nationality = db.Column(db.String(80))
    address = db.Column(db.String(200))
    phone_number = db.Column(db.String(20))
    email_address = db.Column(db.String(120))
    social_media_profiles = db.Column(db.String(500))
    occupation = db.Column(db.String(120))
    company = db.Column(db.String(120))
    job_title = db.Column(db.String(120))
    work_address = db.Column(db.String(200))
    work_phone_number = db.Column(db.String(20))
    work_email_address = db.Column(db.String(120))
    linkedin_profile = db.Column(db.String(120))
    marital_status = db.Column(db.String(20))
    spouse_name = db.Column(db.String(120))
    children_names_ages = db.Column(db.String(500))
    hobbies = db.Column(db.String(500))
    interests = db.Column(db.String(500))
    favorite_books = db.Column(db.String(500))
    favorite_movies = db.Column(db.String(500))
    favorite_music = db.Column(db.String(500))
    notes = db.Column(db.Text)
    date_met = db.Column(db.String(20))
    place_met = db.Column(db.String(120))
    first_impression = db.Column(db.Text)
    how_you_met = db.Column(db.String(500))
    mutual_contacts = db.Column(db.String(500))
    last_meeting_date = db.Column(db.String(20))
    next_meeting_date = db.Column(db.String(20))
